- name: Deploy Redmine app
  hosts: all
  become: true

  tasks:
    - name: Create directory for .env
      ansible.builtin.file:
        path: '/opt/redmine'
        state: directory
        mode: '755'

    - name: Create .env file from template
      ansible.builtin.template:
        src: redmine.env.j2
        dest: '{{ env_file_path }}'
        mode: '644'

    - name: Stop and remove old container if exists
      docker_container:
        name: '{{ container_name }}'
        state: absent
        force_kill: yes
      ignore_errors: yes

    - name: Run Redmine container
      docker_container:
        name: '{{ container_name }}'
        image: '{{ image }}'
        state: started
        restart_policy: unless-stopped
        ports:
          - '{{ redmine_port }}:3000'
        env_file: '{{ env_file_path }}'
