- name: Setup for Docker deployment
  hosts: webservers
  become: yes

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - datadog.dd.agent
