- name: Setup for Docker deployment
  hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - role: datadog.dd.agent
      when: inventory_hostname in groups['webservers']
